baseurl = "gjuha-jon"
publishDir = "docs"
title = "Gjuha Jonë"
theme = "hugo-nederburg-theme"
languageCode = "sqi-aln"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
preserveTaxonomyNames = true
paginate = 5 #frontpage pagination

[taxonomies]
  shkrimtar="shkrimtar"
  disableKinds=["categories", "tags"]

[params]
  slogan = "Përmbledhje e letërsive në gjuhën tonë të bukur shqipe"
  description = "Përmbledhje e letërsive në gjuhën tonë të bukur shqipe" # meta description
  copyright = [
    "&copy; 2018 Edita Dibrani",
    "Nederburg Hugo Theme by [Appernetic](https://appernetic.io)."
  ]

  # Nav links in the side bar
  [[menu.main]]
  name = "Kryefaqja"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Qëllimi"
  url = "qëllimi/"
  weight = 2

  [params.social]
  github        = "https://gjakovaime.github.io/"
